version: "2.1"

services:
  proto-runner:
    build:
      context: .
      dockerfile: ./proto_runner/Dockerfile
    image: proto-runner
    container_name: proto-runner
    volumes:
      - ".:/supply-chain"
    command: |
      bash -c "
        proto_gen
      "

  supply-tp:
    build:
      context: .
      dockerfile: ./processors/Dockerfile
    image: supply-tp
    container_name: supply-tp
    volumes:
      - ".:/supply-chain"
    depends_on:
      - validator
    entrypoint: |
      bash -c "
        sleep 1 && \
        supply_processor -vv -C tcp://validator:4004
      "

  settings-tp:
    image: hyperledger/sawtooth-settings-tp
    container_name: sawtooth-settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator
    container_name: supply-validator
    expose:
      - 4004
      - 8800
    ports:
      - "4004:4004"
    depends_on:
      - proto-runner
    entrypoint: "bash -c \"\
      if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawset proposal create \
          -k /root/.sawtooth/keys/my_key.priv \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          -o config.batch && \
        sawadm genesis config-genesis.batch config.batch; \
      fi; \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
        \""

  devmode-engine:
    image: hyperledger/sawtooth-devmode-engine-rust
    container_name: sawtooth-devmode-engine-rust-default
    depends_on:
      - validator
    entrypoint: devmode-engine-rust -C tcp://validator:5050

  rest-api:
    image: hyperledger/sawtooth-rest-api
    container_name: sawtooth-rest-api
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vv
        --connect tcp://validator:4004
        --bind rest-api:8008

  shell:
    image: hyperledger/sawtooth-shell
    container_name: sawtooth-shell
    depends_on:
      - rest-api
    volumes:
      - ".:/supply-chain"
    entrypoint: "bash -c \"\
      sawtooth keygen --force && \
      tail -f /dev/null \
      \""
